#!/bin/sh
set -eu

host_bin=/host/build/bin/${BUILD_ARCH}-linux-gnu
source_archive=/host/build/sources/illumos-gate-mountin-2026-08-15.tar.gz
binutils_archive=/host/build/sources/binutils-2.46.1.tar.bz2

mkdir -p /build/binutils-source /build/binutils-build
tar -xjf "$binutils_archive" -C /build/binutils-source --strip-components=1
cd /build/binutils-build
../binutils-source/configure \
    --target=x86_64-pc-solaris2.11 \
    --prefix=/opt/illumos-binutils \
    --disable-gdb \
    --disable-gprof \
    --disable-ld \
    --disable-nls \
    --disable-werror
make -j"${JOBS:-1}" all-gas
make install-gas
ln -s x86_64-pc-solaris2.11-as /opt/illumos-binutils/bin/as

install -m 0755 "$host_bin/dmake" /usr/local/bin/dmake
mkdir -p /opt/schily/lib
install -m 0644 "$host_bin/lib/libmakestate.so.1" \
    /opt/schily/lib/libmakestate.so.1
mkdir -p /opt/qemount/libelf
install -m 0644 "$host_bin/lib/64/libelf.so.1" \
    /opt/qemount/libelf/libelf.so.1

mkdir -p /source
tar -xzf "$source_archive" -C /source --strip-components=1

src=/source/usr/src
onbld=$src/tools/proto/root_i386-nd/opt/onbld
makefile=$src/cmd/make/bin/make.rules.file

run_make()
{
    directory=$1
    target=$2
    shift 2
    cd "$directory"
    dmake -r -f "$makefile" -f Makefile \
        "MAKE=dmake -r -f $makefile -f Makefile" \
        SRC="$src" CODEMGR_WS=/source \
        MACH=i386 MACH64=amd64 NATIVE_MACH=amd64 NATIVE_MACH64=amd64 \
        RELEASE_BUILD= NATIVE_OS=linux \
        GNU_ROOT=/opt/illumos-binutils \
        GNUC_ROOT=/usr NATIVE_GNUC_ROOT=/usr \
        ONBLD_TOOLS="$onbld" \
        "$@" "$target"
}

run_make "$src/tools" bootstrap

# libconv and libelf are prerequisites of the illumos archive editor itself.
# Bootstrap just those two native libraries with the host archive editor, then
# use the resulting illumos ar for every subsequent target build.
run_make "$src/tools/sgs/include" install
run_make "$src/tools/sgs/sgsmsg" install
run_make "$src/tools/sgs/libconv" install AR=/usr/bin/ar
run_make "$src/tools/sgs/libelf" install AR=/usr/bin/ar
run_make "$src/tools/sgs/ar" install AR=/usr/bin/ar
run_make "$src/tools/sgs" install
run_make "$src/tools/rpcgen" install
run_make "$src/tools/elfextract" install
run_make "$src/tools/mbh_patch" install
run_make "$src/tools/vtfontcvt" install
run_make "$src/tools/scripts" "$onbld/bin/genoffsets"

# lorder is a portable shell program in illumos-gate.  It runs the native
# nm, so install it as a host build tool rather than building a target binary.
sed "s|^WHERE=/usr/bin$|WHERE=$onbld/bin/i386|" \
    "$src/cmd/sgs/lorder/lorder.sh" > /usr/local/bin/lorder
chmod 0755 /usr/local/bin/lorder

# The native CTF tools are linked against the host libelf API. Debian
# bookworm's libelf mishandles the archive tables generated by illumos ar, so
# keep the newer implementation private to those tools rather than changing
# the native link-editor's illumos libelf dependency.
mkdir -p "$onbld/lib/i386/elfutils"
install -m 0644 /opt/qemount/libelf/libelf.so.1 \
    "$onbld/lib/i386/elfutils/libelf.so.1"
