exit
cd /build
ls -l
cd diod-1.0.24
ls -l
make
apt update
apt search xattr
apt install xattr
apt install xattr --yes
make
apt search libxattr
apt search libattr
apt install libattr1-dev
make
ls -l
less INSTALL
pwd
exit
