FROM alpine:3.23

RUN apk add --no-cache \
    bash \
    bison \
    build-base \
    flex \
    gawk \
    linux-headers \
    make \
    patch \
    perl \
    python3 \
    rsync \
    tar \
    texinfo \
    xz

WORKDIR /build
